default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: '123456'

development:
  <<: *default
  database: corrientazo_development

test:
  <<: *default
  database: corrientazo_test


production:
  <<: *default
  database: corrientazo_production
